[package]
name = "color-reduce"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-math = "0.1.1"
image = {version="0.23.14", default-features = false}
lab = "0.7.2"