[package]
name = "color-reduce"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-math = {version="0.1.1", features=[]}
image = "0.23.14"
lab = "0.7.2"